import type { Config } from 'tailwindcss';

const config: Config = {
  content: [
    './app/**/*.{ts,tsx}',
    './components/**/*.{ts,tsx}',
    './lib/**/*.{ts,tsx}',
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        primary: {
          DEFAULT: '#f2ca50',
          50: '#EFF6FF',
          100: '#DBEAFE',
          200: '#BFDBFE',
          300: '#93C5FD',
          400: '#60A5FA',
          500: '#3B82F6',
          600: '#2563EB',
          700: '#1D4ED8',
          800: '#1E3A8A',
          900: '#1E3A5C',
          'fixed': '#ffe088',
          'fixed-dim': '#e9c349',
          'fixed-variant': '#574500',
        },
        accent: '#3B82F6',
        surface: {
          DEFAULT: '#16130b',
          bg: '#F8FAFC',
          border: '#E2E8F0',
          hover: '#F1F5F9',
        },
        brand: {
          primary: 'var(--brand-primary)',
          secondary: 'var(--brand-secondary)',
        },
        // Stitch design system colors
        "on-secondary-container": "#fada77",
        "tertiary": "#bfcdff",
        "on-tertiary-container": "#254188",
        "on-primary-fixed-variant": "#574500",
        "surface-dim": "#16130b",
        "outline": "#99907c",
        "on-surface-variant": "#d0c5af",
        "on-secondary": "#3c2f00",
        "on-secondary-fixed-variant": "#564500",
        "on-error-container": "#ffdad6",
        "primary-container": "#d4af37",
        "background": "#16130b",
        "on-background": "#eae1d4",
        "surface-container-low": "#1f1b13",
        "inverse-primary": "#735c00",
        "surface-container-high": "#2d2a21",
        "tertiary-fixed-dim": "#b4c5ff",
        "on-secondary-fixed": "#231b00",
        "on-surface": "#eae1d4",
        "secondary-container": "#755e00",
        "primary-fixed": "#ffe088",
        "on-primary-container": "#554300",
        "secondary": "#e3c464",
        "inverse-surface": "#eae1d4",
        "tertiary-container": "#97b0ff",
        "on-error": "#690005",
        "on-tertiary-fixed-variant": "#27438a",
        "on-primary": "#3c2f00",
        "surface-container-lowest": "#110e07",
        "error-container": "#93000a",
        "surface-variant": "#38342b",
        "surface-container": "#231f17",
        "secondary-fixed-dim": "#e3c464",
        "surface-tint": "#e9c349",
        "tertiary-fixed": "#dbe1ff",
        "on-primary-fixed": "#241a00",
        "on-tertiary": "#082b72",
        "inverse-on-surface": "#343027",
        "surface-container-highest": "#38342b",
        "error": "#ffb4ab",
        "on-tertiary-fixed": "#00174b",
        "surface-bright": "#3d392f",
        "secondary-fixed": "#ffe083",
        "outline-variant": "#4d4635",
        "primary-fixed-dim": "#e9c349",
        "primary-fixed-variant": "#574500",
      },
      fontFamily: {
        sans: ['var(--font-inter)', 'system-ui', '-apple-system', 'sans-serif'],
        "title-md": ["Hanken Grotesk"],
        "body-lg": ["Inter", "sans-serif"],
        "label-sm": ["Geist"],
        "headline-lg": ["Hanken Grotesk"],
        "body-md": ["Inter", "sans-serif"],
        "display-lg": ["Sora", "sans-serif"],
        "headline-lg-mobile": ["Hanken Grotesk"],
        "display-lg-mobile": ["Sora", "sans-serif"],
        "label-caps": ["Inter", "sans-serif"],
        "headline-md": ["Sora", "sans-serif"],
      },
      borderRadius: {
        card: '14px',
      },
      spacing: {
        "unit": "8px",
        "gutter": "24px",
        "container-padding-mobile": "20px",
        "container-padding-desktop": "40px",
        "section-gap": "80px"
      },
      maxWidth: {
        content: '1100px',
      },
      boxShadow: {
        card: '0 1px 3px rgba(0,0,0,0.04), 0 4px 12px rgba(0,0,0,0.06)',
        'card-hover': '0 4px 16px rgba(0,0,0,0.08), 0 8px 32px rgba(0,0,0,0.06)',
        nav: '0 1px 3px rgba(0,0,0,0.04)',
      },
      fontSize: {
        'hero': ['3rem', { lineHeight: '1.1', fontWeight: '800' }],
        'hero-mobile': ['1.75rem', { lineHeight: '1.2', fontWeight: '800' }],
        "title-md": ["20px", { lineHeight: "1.4", letterSpacing: "0.02em", fontWeight: "500" }],
        "body-lg": ["20px", { lineHeight: "1.6", fontWeight: "300" }],
        "label-sm": ["12px", { lineHeight: "1", letterSpacing: "0.1em", fontWeight: "600" }],
        "headline-lg": ["40px", { lineHeight: "1.2", letterSpacing: "-0.01em", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "display-lg": ["64px", { lineHeight: "1.05", letterSpacing: "-0.04em", fontWeight: "800" }],
        "headline-lg-mobile": ["32px", { lineHeight: "1.2", letterSpacing: "-0.01em", fontWeight: "600" }],
        "display-lg-mobile": ["42px", { lineHeight: "1.1", fontWeight: "800" }],
        "label-caps": ["12px", { lineHeight: "1.0", letterSpacing: "0.15em", fontWeight: "600" }],
        "headline-md": ["36px", { lineHeight: "1.2", fontWeight: "700" }],
      },
      keyframes: {
        'fade-in': {
          '0%': { opacity: '0', transform: 'translateY(8px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        'slide-up': {
          '0%': { opacity: '0', transform: 'translateY(100%)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        'slide-down': {
          '0%': { opacity: '0', transform: 'translateY(-8px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        shimmer: {
          '0%': { backgroundPosition: '-200% 0' },
          '100%': { backgroundPosition: '200% 0' },
        },
      },
      animation: {
        'fade-in': 'fade-in 0.4s ease-out forwards',
        'slide-up': 'slide-up 0.35s ease-out forwards',
        'slide-down': 'slide-down 0.3s ease-out forwards',
        shimmer: 'shimmer 1.5s ease-in-out infinite',
      },
    },
  },
  plugins: [],
};

export default config;
